#data

data_dir: "C:/FAV/FAV/3.rocnik/bakalarka/ZCU_dataset/data"


#training
strategy: "per_person"  # Options: "all", "per_person"
batch_size: 128
epochs: 10
lr: 0.0001
preferred_device: gpu
nGPU: 0

#model
network_args:
  num_classes: 3
  num_channels: 3
  num_samples: 2000
  embed_dim: 24
  pool_size: 50
  pool_stride: 20
  num_heads: 8
  fc_ratio: 4
  depth: 3
  attn_drop: 0.7
  fc_drop: 0.7

# Data augmentation
num_classes: 3
num_segs: 5