#data
csv_files: "../103_data/eegmmidb"

#training
strategy: "per_person"  # Options: "all", "per_person"
batch_size: 64
epochs: 7
lr: 0.0002
preferred_device: gpu
nGPU: 0

#model
network_args:
  num_classes: 2
  num_channels: 64
  num_samples: 1000
  embed_dim: 32
  pool_size: 50
  pool_stride: 15
  num_heads: 8
  fc_ratio: 4
  depth: 4
  attn_drop: 0.5
  fc_drop: 0.5

# Data augmentation
num_classes: 2
num_segs: 5